export const subValues = {
    "Core Switch": [
      "Core SW to Palo Alto - P 33",
      "Core SW to Fortigate - P 40",
      "Core SW to Fortigate - P 41",
      "Core SW to Fortigate - P 42",
      "Core SW to Fortigate - P 43",
      "ADVANTIS HO BUILDING - P 50",
      "ADVANTIS MIT (400 DEANS RD) - P 51",
      "ADVANTIS DC (SVR FARM SW) - P 52",
      "HAYCARB HO (DEANS RD) - P 81",
      "FIBER HO (FOSTER LN) - P 83",
      "CONSUMER (FOSTER LANE) - P 84",
      "AVENTURA (FOSTER LANE) - P 85",
      "AGRO (FOSTER LANE) - P 86",
      "DPL HO (DEANS RD) - P 87",  
      "TTEL HO (DEANS RD) - P 88",
      "KVPL (400 DEANS RD) - P 89",
      "CORE ROUTERS (MPLS) - P 103",
      "CORE ROUTERS (MPLS) - P 104",
      "SERVER FARM (SW STACK) 1 - P 109",
      "DEANS RD (SW) - P 122",
      "SERVER FARM (SW STACK) 2 - P 123",
      "HBSI (TWE 1/6/0/24) | (TWE 1/6/0/26)",
    ],
    "WAN Firewall": [
      "ADV-3PL-Kelaniya",
      "ADV-3PL-Kotugoda",
      "ADV-Expelogixs",
      "ADV-Hayleys Free Zone 1-Venus",
      "ADV-Hayleys Free Zone 2-Mecury",
      "ADV-Logiwiz Kelanimulla",
      "ADV-LIL-Wallampitiya",
      "Fiber-Chas.P Galle",
      "Fiber-Chas.P Madampe",
      "Fiber-Chas.P Naththandiya",
      "Fiber-Creative Polymat",
      "Fiber-Kuliyapitiya",
      "Fiber-Ravi Industries",
      "Fiber-Rileys Katana",
      "Fiber-Volanka Kotugoda",
      "Agro-HJS",
      "Agro-Biotech Nanuoya",
      "Agro-Seeduwa *",
      "Agro-Haychem Kottawa *",
      "Agro-Animal Health Sapugaskanda *",
      "Agro-Pannipitiya *",
      "Agro-QS_Hokandara *",
      "Agro-Fertilizer *",
      "Agro-Quality Seeds Boralanda 1 *",
      "Agro-Quality Seeds Boralanda 2",
      "Agro-CocoLife Pannala",
      "Agro-Technica Ekala",
      "Fabric Neboda",
      "Fabric Wagawaththa",
      "Amaya Kandyan Resort",
      "Amaya Kingsbury",
      "Amaya Lake Dambulla",
      "Amaya Leisure WTC",
      "Amaya Sunset Beach",
      "Alumex Gonawala",
      "Alumex Ho Makola",
      "Alumex Prime",
      "DPL-Premier Gloves Biyagama",
      "DPL-Sport Gloves Biyagama",
      "DPL-Uni Gloves Biyagama",
      "DPL-Hanwella",
      "DPL-Kottawa",
      "South Asian Textiles",
      "Haycarb-Badalgama",
      "Haycarb-Madampe",
      "Haycarb-Wewalduwa",
      "Mabroc-Tea",
    ],
    "Access & Distribution Switches": [
      "PLC_GIT",
      "PLC_ESD",
      "PLC_SECRETARIAL",
      "PLC_FINANCE",
      "PLC_CPMD",
      "PLC_GHR",
      "PLC_SBDU",
      "KVPL",
      "AVENTURA",
      "DPL_HO",
      "HBSI",
      "HO_ROUTER",
      "FL_ROUTER",
      "DEANS-ROAD-CORE-STACK",
      "ESD-SWITCH",
      "NEW-DC-STACK",
      "NEW-DC-VM-STACK",
      "SBDU_SW1",
    ],
  };
  
  export const non24x7SubValues = [
    "Agro-Seeduwa *",
    "Agro-Haychem Kottawa *",
    "Agro-Animal Health Sapugaskanda *",
    "Agro-Pannipitiya *",
    "Agro-QS_Hokandara *",
    "Agro-Fertilizer *",
    "Agro-Quality Seeds Boralanda 1 *",
  ];

  // Access Points Availability
  subValues["Access Points Availability"] = [
    // GROUP_IT
    "AP_01-GRIT_01-30",
    "AP_109-HBSI-162",
    "AP_03-TREASURY_01-122",
    "AP 26-TREASURY BR-123",
    "AP_34-HAY_SEC_02-20",
    "AP_35-HAY_FIN_01-21",
    "AP_13-LEGAL_01-72",
    "AP_40-GFM_01-140",
    "AP 08-GHR 01-78",
    "AP_32-CONFERENCE_01-10",
    "AP_16-ADV_AST_GLOBAL_01-121",
    // ADVANTIS
    "AP 07-ADV HO 04-119",
    "AP 37-ADV HO 02-117",
    "AP 39-ADV HO 03-118",
    "AP_28-ADV_CLSH_01-112",
    "AP 43-ADV CLSH 02-116",
    "AP 21-ADV CLSH 02-123",
    "AP_29-ADV_NYK_01-113",
    "AP_33-ADV_AVTN_01-115",
    "AP 30-ADV VSTR 01-114",
    // HAYCARB
    "AP 88-HAYCARB 05-76",
    "AP 49-HAYCARB 04-75",
    "AP_11-HAYCARB_01-70",
    "AP_108-HAYCARB_06-77",
    "AP_12-HAYCARB_02-71",
    "AP 42-HAYCARB 03-74",
    "AP_18-PURITAS_01-90",
    // AVENTURA
    "AP_23-AVENTURA_02-51",
    "AP_19-AVENTURA_01-50",
    "AP_20-AVENTURA_03-53",
    // HPL (Horana Plantation)
    "AP_123-HPL_01-181",
    // KVPL (Kelani Valley Plantations)
    "AP_27-KVPL_01-65",
    // LEISURE
    "AP_24-LIFE_SCINCES_01-52",
    // AGRO
    "AP_90-AGRO_05-64",
    "AP_89-AGRO_04-63",
    "AP_04-AGRO_01-67",
    // CONSUMER
    "AP_05-CONSUMER_01-40",
    // FIBRE
    "AP_15-FIBRE_01-120",
    // DPL
    "AP_25-DPL_01-155",
    "AP_06-DPL_02-156",
    // CPMD
    "AP_38-CPMD_01-55",
    // TTEL
    "AP_22-TTEL_01-245",
    // MARTIN BOURE
    "AP_31-HGBL_01-26",
  ];