export const subValues = {
    "Core Switch": [
      "Core SW to Palo Alto - P 33",
      "Core SW to Fortigate - P 40",
      "Core SW to Fortigate - P 41",
      "Core SW to Fortigate - P 42",
      "Core SW to Fortigate - P 43",
      "ADVANTIS HO BUILDING - P 50",
      "ADVANTIS MIT (400 DEANS RD) - P 51",
      "ADVANTIS DC (SVR FARM SW) - P 52",
      "HAYCARB HO (DEANS RD) - P 81",
      "FIBER HO (FOSTER LN) - P 83",
      "CONSUMER (FOSTER LANE) - P 84",
      "AVENTURA (FOSTER LANE) - P 85",
      "AGRO (FOSTER LANE) - P 86",
      "DPL HO (DEANS RD) - P 87",
      "TTEL HO (DEANS RD) - P 88",
      "KVPL (400 DEANS RD) - P 89",
      "CORE ROUTERS (MPLS) - P 103",
      "CORE ROUTERS (MPLS) - P 104",
      "SERVER FARM (SW STACK) 1 - P 109",
      "DEANS RD (SW) - P 122",
      "SERVER FARM (SW STACK) 2 - P 123",
    ],
    "WAN Firewall": [
      "ADV-3PL-Kelaniya",
      "ADV-3PL-Kotugoda",
      "ADV-Expelogixs",
      "ADV-Hayleys Free Zone 1-Venus",
      "ADV-Hayleys Free Zone 2-Mecury",
      "ADV-Logiwiz Kelanimulla",
      "ADV-LIL-Wallampitiya",
      "Fiber-Chas.P Galle",
      "Fiber-Chas.P Madampe",
      "Fiber-Chas.P Naththandiya",
      "Fiber-Creative Polymat",
      "Fiber-Kuliyapitiya",
      "Fiber-Ravi Industries",
      "Fiber-Rileys Katana",
      "Fiber-Volanka Kotugoda",
      "Agro-HJS",
      "Agro-Biotech Nanuoya",
      "Agro-Seeduwa *",
      "Agro-Haychem Kottawa *",
      "Agro-Animal Health Sapugaskanda *",
      "Agro-Pannipitiya *",
      "Agro-QS_Hokandara *",
      "Agro-Fertilizer *",
      "Agro-Quality Seeds Boralanda 1 *",
      "Agro-Quality Seeds Boralanda 2",
      "Agro-CocoLife Pannala",
      "Agro-Technica Ekala",
      "Fabric Neboda",
      "Fabric Wagawaththa",
      "Amaya Kandyan Resort",
      "Amaya Kingsbury",
      "Amaya Lake Dambulla",
      "Amaya Leisure WTC",
      "Amaya Sunset Beach",
      "Alumex Gonawala",
      "Alumex Ho Makola",
      "Alumex Prime",
      "DPL-Premier Gloves Biyagama",
      "DPL-Sport Gloves Biyagama",
      "DPL-Uni Gloves Biyagama",
      "DPL-Hanwella",
      "DPL-Kottawa",
      "South Asian Textiles",
      "Haycarb-Badalgama",
      "Haycarb-Madampe",
      "Haycarb-Wewalduwa",
      "Mabroc-Tea",
    ],
    "Access & Distribution Switches": [
      "PLC_GIT",
      "PLC_ESD",
      "PLC_SECRETARIAL",
      "PLC_FINANCE",
      "PLC_CPMD",
      "PLC_GHR",
      "PLC_SBDU",
      "KVPL",
      "AVENTURA",
      "DPL_HO",
      "HBSI",
      "HO_ROUTER",
      "FL_ROUTER",
    ],
  };
  
  export const non24x7SubValues = [
    "Agro-Seeduwa *",
    "Agro-Haychem Kottawa *",
    "Agro-Animal Health Sapugaskanda *",
    "Agro-Pannipitiya *",
    "Agro-QS_Hokandara *",
    "Agro-Fertilizer *",
    "Agro-Quality Seeds Boralanda 1 *",
  ];